### ISSUE TITLE
The project document has the wrong color when in dark mode

### ISSUE THREAD

**Issue by soup-Lee** [tusen-ai/naive-ui#4381]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Microsoft Edge 109.0.1518.55

### System and its version (系统及其版本)
Windows11

### Node version (Node 版本)
22H2

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/button

### Reappearance steps (重现步骤)
1.Open the project document
2.Switch to dark mode

### Expected results (期望的结果)
Normal dark mode

### Actual results (实际的结果)
In the content section, there is a white color that should not be seen

### Remarks (补充说明)
I don't know if I should file it here, but I've found out it's been a long time since this happened, and sorry if the report is in the wrong place

**Comment by faga295** [comment]
did you talking about this?
![image](https://user-images.githubusercontent.com/87003751/213485513-aae215e8-12aa-45b6-87fb-0d3b0cd3abb6.png),if not, could you please point out where the white color is.
It seems like this problem has been fixed at current branch
![image](https://user-images.githubusercontent.com/87003751/213486444-55d2e3b2-fac3-4de4-91d4-c5f84bcdfd82.png)

**Comment by soup-Lee** [comment]
I tried to force a page refresh, but the problem persisted, and this is what I saw：
![image](https://user-images.githubusercontent.com/79054161/213487133-d47b806a-0f77-4c65-be2e-1203e13941a1.png)

**Comment by faga295** [comment]
magical, maybe this is a production environment bug

**Comment by soup-Lee** [comment]
maybe,This error doesn't happen when I use Firefox,Maybe it's my browser. I'm sorry if it disturbs you
